version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ../env/.env
    depends_on:
      - db
    networks:
      - test_network

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env
    networks:
      - test_network

networks:
  test_network:
    name : test_network
