version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ../env/.env
    volumes:
      - ..:/app
    depends_on:
      - db
    networks:
      - local_network

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  db-data:

networks:
  local_network:
    name : local_network
