# Generated by Django 4.2.19 on 2025-02-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "후기",
                "verbose_name_plural": "후기",
            },
        ),
    ]
